import type { Rule } from './types';
import { anyOf, has, isNum, possiblyAge, years } from './helpers';
import { CITE, SRC } from './sources';

const PCPNC_D28_SHORT = `${CITE.WHO_PCPNC_2015}, cuadro D28 posparto ("severe depression or suicidal behaviour (ideas or attempts)": "as soon as possible")`;

const CALL_911 = 'Llamar al 911 o conseguir transporte AHORA al hospital. No esperar a ver si mejora.';

export const ADULT_RULES: Rule[] = [
  {
    id: 'IITT-R-RESP-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, years(5)) && has(f, 'dificultad_respirar'),
    explicacion: { es: 'Persona de 5 años o más con dificultad para respirar.', nah: '' },
    accion: { es: `${CALL_911} Dejarla sentada en la posición en que respire mejor.`, nah: '' },
    fuente: `${CITE.IITT}, criterio rojo "Respiratory distress or central cyanosis" (≥12 años) y "Respiratory distress* or central cyanosis" (pediátrico, <12 años)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['dificultad_respirar', 'edad_meses'],
    fidelidad: 'adaptado',
  },
  {
    id: 'CDC-STROKE-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) =>
      anyOf(f, 'cara_caida', 'debilidad_un_lado', 'dificultad_hablar', 'confusion', 'perdida_equilibrio', 'dolor_cabeza_subito', 'perdida_vision_subita'),
    explicacion: {
      es: 'Signos de posible derrame cerebral (embolia): de repente cara caída, debilidad o adormecimiento de un lado, dificultad para hablar, confusión, pérdida del equilibrio, pérdida de la vista o dolor de cabeza súbito muy fuerte.',
      nah: '',
    },
    accion: {
      es: `${CALL_911} Anotar la HORA en que empezaron los síntomas. No dar nada de comer ni beber.`,
      nah: '',
    },
    fuente: `${CITE.CDC_STROKE}: "Sudden numbness or weakness in the face, arm, or leg, especially on one side", "Sudden trouble seeing", "Sudden confusion, trouble speaking", "Sudden trouble walking, dizziness, loss of balance", "Sudden severe headache"… "Call 9-1-1 right away"`,
    fuente_url: SRC.CDC_STROKE,
    needs: ['cara_caida', 'debilidad_un_lado', 'dificultad_hablar', 'confusion', 'perdida_equilibrio', 'dolor_cabeza_subito', 'perdida_vision_subita'],
    fidelidad: 'verbatim',
  },
  {
    id: 'CDC-HEART-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, years(12)) && has(f, 'dolor_pecho'),
    explicacion: { es: 'Persona de 12 años o más con dolor u opresión en el pecho (posible infarto).', nah: '' },
    accion: { es: `${CALL_911} Mantenerla en reposo, sentada, sin hacer esfuerzo.`, nah: '' },
    fuente: `${CITE.CDC_HEART_ATTACK}: "Chest pain or discomfort"… "Call 9-1-1 if you notice symptoms of a heart attack"; ${CITE.IITT}: rojo "Acute chest or abdominal pain (>50 years old)"`,
    fuente_url: SRC.CDC_HEART_ATTACK,
    needs: ['dolor_pecho', 'edad_meses'],
    context: ['dificultad_respirar', 'sudor_frio'],
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-R-SNAKE-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => has(f, 'mordedura_serpiente'),
    explicacion: { es: 'Mordedura de víbora.', nah: '' },
    accion: {
      es: `${CALL_911} Mantener quieta a la persona y la extremidad mordida. No cortar, no chupar, no poner torniquete ni hielo.`,
      nah: '',
    },
    fuente: `${CITE.IITT}, criterio rojo "Snake bite" (tablas adulto y pediátrica)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['mordedura_serpiente'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-R-POISON-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => has(f, 'intoxicacion'),
    explicacion: { es: 'Tomó veneno, plaguicida u otro químico peligroso.', nah: '' },
    accion: {
      es: `${CALL_911} Llevar el envase o la etiqueta del producto. No provocar el vómito. Quitar la ropa contaminada y lavar la piel con agua si hubo contacto.`,
      nah: '',
    },
    fuente: `${CITE.IITT}, criterio rojo "Poisoning/ingestion or dangerous chemical exposure" (tablas adulto y pediátrica)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['intoxicacion'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-R-TRAUMA-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => has(f, 'trauma_grave'),
    explicacion: { es: 'Golpe o accidente grave (trauma de alto riesgo).', nah: '' },
    accion: { es: `${CALL_911} No mover el cuello ni la espalda si cayó de altura o fue atropellado. Apretar las heridas que sangran.`, nah: '' },
    fuente: `${CITE.IITT}, criterio rojo "High-risk trauma" (tablas adulto y pediátrica)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['trauma_grave'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-R-SHOCK-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, 0, years(12)) && has(f, 'manos_pies_frios'),
    explicacion: { es: 'Niño con manos y pies fríos (posible choque / mala circulación).', nah: '' },
    accion: { es: 'Referir URGENTE al hospital: conseguir transporte o llamar al 911 ahora. Mantenerlo abrigado.', nah: '' },
    fuente: `${CITE.IITT} pediátrico (<12 años), criterio rojo "Cold extremities"`,
    fuente_url: SRC.IITT_PED,
    needs: ['manos_pies_frios', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-BITE-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) => has(f, 'mordedura_animal'),
    explicacion: { es: 'Mordedura o rasguño de animal (perro, gato, murciélago u otro).', nah: '' },
    accion: {
      es: 'Lavar la herida con agua y jabón abundante durante 15 minutos. Llevar HOY a la unidad de salud: puede necesitar vacuna antirrábica, que es urgente en tiempo.',
      nah: '',
    },
    fuente: `${CITE.IITT}, criterio amarillo "Exposure requiring time-sensitive prophylaxis (eg. animal bite…)"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['mordedura_animal'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-TRAUMA-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) => anyOf(f, 'fractura', 'quemadura'),
    explicacion: { es: 'Posible hueso roto, miembro deformado o quemadura.', nah: '' },
    accion: {
      es: 'Inmovilizar la parte lastimada como esté. Si es quemadura: enfriar con agua limpia (no hielo, no pomadas caseras). Llevar HOY a la unidad de salud.',
      nah: '',
    },
    fuente: `${CITE.IITT}, criterios amarillos "Visible acute limb deformity", "Open fracture", "Other trauma/burns (no red criteria)"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['fractura', 'quemadura'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-BLEED-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) =>
      anyOf(f, 'sangrado', 'vomito_sangre', 'heces_negras', 'sangrado_mucosas') || (possiblyAge(f, years(5)) && has(f, 'sangre_heces')),
    explicacion: { es: 'Sangrado que continúa (no abundante): herida, encías o nariz, vómito con sangre, popó negra o con sangre.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Si el sangrado aumenta o se marea/desmaya: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT}, criterio amarillo "Ongoing bleeding (no red criteria)"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['sangrado', 'vomito_sangre', 'heces_negras', 'sangre_heces', 'sangrado_mucosas'],
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-Y-FAINT-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) => possiblyAge(f, years(12)) && anyOf(f, 'desmayo', 'mareo_al_pararse'),
    explicacion: { es: 'Desmayo reciente, o se marea o se desvanece al pararse.', nah: '' },
    accion: { es: 'Acostarlo con las piernas levantadas. Llevar HOY a la unidad de salud. Si tiene dolor de pecho o no despierta: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT} (≥12 años), criterio amarillo "Recent fainting"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['desmayo', 'mareo_al_pararse', 'edad_meses'],
    // adaptado: se incluye el mareo al pararse (casi-desmayo), que no está literal en el IITT.
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-Y-WEAK-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) => (possiblyAge(f, years(12)) && has(f, 'debilidad_general')) || (possiblyAge(f, years(5)) && has(f, 'letargico')),
    explicacion: { es: 'Debilidad general de inicio reciente o anormalmente dormido (mayor de 5 años).', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Si no despierta, convulsiona o tiene dificultad para respirar: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT}, criterios amarillos "Acute general weakness", "Altered mental status or agitation" (≥12 años) y "Restless, continuously irritable or lethargy" (<12 años)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['debilidad_general', 'letargico', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-PAIN-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) => anyOf(f, 'dolor_intenso', 'dolor_abdominal_intenso'),
    explicacion: { es: 'Dolor muy fuerte.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud para valoración.', nah: '' },
    fuente: `${CITE.IITT}, criterio amarillo "Severe pain (no red criteria)" (tablas adulto y pediátrica)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['dolor_intenso', 'dolor_abdominal_intenso'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-URINE-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) => possiblyAge(f, years(12)) && has(f, 'no_puede_orinar'),
    explicacion: { es: 'No puede orinar.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud.', nah: '' },
    fuente: `${CITE.IITT} (≥12 años), criterio amarillo "Unable to pass urine"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['no_puede_orinar', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-VS-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) =>
      possiblyAge(f, years(12)) &&
      ((isNum(f.resp_por_min) && f.resp_por_min > 30) || (isNum(f.temperatura_c) && (f.temperatura_c > 39 || f.temperatura_c < 36))),
    explicacion: { es: 'Signos vitales de alto riesgo (más de 30 respiraciones por minuto, o temperatura mayor de 39 °C o menor de 36 °C).', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud para valoración por personal clínico.', nah: '' },
    fuente: `${CITE.IITT} (≥12 años), "High-risk vital signs": "RR <10 or >30", "Temp <36° or >39°" → "up-triage or immediate review by supervising clinician" (no se capturan FC, SpO2 ni AVPU)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['resp_por_min', 'temperatura_c', 'edad_meses'],
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-VS-02',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => isNum(f.resp_por_min) && f.resp_por_min < 10,
    explicacion: { es: 'Respira muy lento (menos de 10 respiraciones por minuto): puede dejar de respirar.', nah: '' },
    accion: { es: `${CALL_911} Vigilar que siga respirando; si deja de respirar, iniciar respiración de rescate si sabe hacerlo.`, nah: '' },
    fuente: `${CITE.IITT}, "High-risk vital signs": "RR <10" (≥12 años) y "RR 5-12 years Low 10" (pediátrico) → "up-triage or immediate review"; en comunidad no hay clínico en el lugar, así que se traslada de inmediato`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['resp_por_min'],
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-R-ABD-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, years(50)) && has(f, 'dolor_abdominal_intenso'),
    explicacion: { es: 'Persona mayor de 50 años con dolor de panza fuerte de inicio reciente.', nah: '' },
    accion: { es: `${CALL_911} No darle de comer ni medicinas para el dolor mientras la valoran.`, nah: '' },
    fuente: `${CITE.IITT} (≥12 años), criterio rojo "Acute chest or abdominal pain (>50 years old)"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['dolor_abdominal_intenso', 'edad_meses'],
    // adaptado: el IITT dice ">50"; aquí se incluye a los 50 cumplidos y la edad desconocida (más conservador).
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-R-SHOCK-02',
    block: 'adult',
    level: 'urgencia',
    applies: (f) =>
      anyOf(f, 'llenado_capilar_lento', 'pulso_debil_rapido') ||
      (possiblyAge(f, years(12)) &&
        has(f, 'manos_pies_frios') &&
        anyOf(f, 'sudor_frio', 'mareo_al_pararse', 'desmayo', 'debilidad_general', 'letargico', 'confusion', 'diarrea', 'vomito', 'vomita_todo', 'sangrado', 'sangrado_abundante', 'vomito_sangre', 'heces_negras')),
    explicacion: { es: 'Signos de choque (mala circulación): la uña tarda en ponerse rosa, pulso débil y rápido, o manos y pies fríos con sudor frío, mareo, debilidad, sangrado, diarrea o vómito.', nah: '' },
    accion: { es: `${CALL_911} Acostarla con las piernas levantadas y abrigarla. Si puede beber, sorbos de Vida Suero Oral.`, nah: '' },
    fuente: `${CITE.IITT}, criterios rojos "Capillary refill >3 sec", "Weak and fast pulse" (tablas adulto y pediátrica) y "Cold extremities" (pediátrica)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['llenado_capilar_lento', 'pulso_debil_rapido', 'manos_pies_frios', 'edad_meses'],
    context: ['manos_pies_frios', 'sudor_frio', 'mareo_al_pararse', 'desmayo'],
    // adaptado: en ≥12 años las manos frías solas no bastan (pueden ser por clima); se exige un signo acompañante.
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-Y-VISION-01',
    block: 'adult',
    level: 'centro_hoy',
    applies: (f) => possiblyAge(f, years(12)) && has(f, 'vision_borrosa'),
    explicacion: { es: 'Persona de 12 años o más con visión borrosa o que ve lucecitas de inicio reciente.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud (tomar la presión). Si de repente dejó de ver, tiene la cara chueca o no puede mover un lado: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT} (≥12 años), criterio amarillo "Acute visual disturbance"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['vision_borrosa', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'MHGAP-SUI-01',
    block: 'adult',
    level: 'urgencia',
    applies: (f) => has(f, 'ideas_suicidas'),
    explicacion: { es: 'Dice que se quiere morir, hacerse daño o quitarse la vida (riesgo inminente de suicidio).', nah: '' },
    accion: {
      es: 'NO dejar sola a la persona. Retirar medicinas, venenos, plaguicidas, cuerdas y armas a su alcance. Llevarla HOY MISMO, acompañada, a la unidad de salud o al hospital. Línea de la Vida (México): 800 911 2000, las 24 horas.',
      nah: '',
    },
    fuente: `${CITE.WHO_MHGAP_2016}, módulo SUI: "Current thoughts or plan of self-harm/suicide" → "IMMINENT RISK OF SELF-HARM/SUICIDE is likely"; SUI 2: "Place the person in a secure and supportive environment at a health facility", "DO NOT leave the person alone"; ${PCPNC_D28_SHORT}`,
    fuente_url: SRC.WHO_MHGAP_2016,
    needs: ['ideas_suicidas'],
    context: ['depresion_grave'],
    fidelidad: 'adaptado',
  },
];
