/**
 * Ronda 3 (4-oct-2026): signos de alarma de molestias comunes de primer nivel.
 * Base: docs/research-common-complaints.md. Cada cita se volvió a leer en la fuente al escribir la regla
 * (PDF descargado y texto extraído, o página web consultada el 4-oct-2026). No se cambió ningún umbral ni nivel
 * de las reglas existentes. Todas son PROVISIONALES: pendientes de revisión de la Dra. Ines.
 *
 * Equivalencias de nivel para las fuentes nuevas (docs/clinical-sources.md §1):
 *  - NHS "Call 999 / go to A&E", SSA "urgencia médica", IMSS "referir a urgencias de forma inmediata", IITT rojo → urgencia.
 *  - NHS "urgent GP appointment / NHS 111", IITT amarillo, CENAPRECE "lo más pronto posible a la unidad de salud",
 *    tratamiento que solo da el médico (antibiótico, antídoto en observación) → centro_hoy.
 */
import type { Rule } from './types';
import { anyOf, has, hasFever, isNum, isPregnant, knownAge, possiblyAge, years } from './helpers';
import { CITE, SRC } from './sources';

const CALL_911 = 'Llamar al 911 o conseguir transporte AHORA al hospital. No esperar a ver si mejora.';
const NO_CORTAR = 'No corte, no chupe, no ponga torniquete ni remedios caseros: retrasan la atención.';

const alacran = (f: Parameters<Rule['applies']>[0]) => has(f, 'picadura_alacran');
const arana = (f: Parameters<Rule['applies']>[0]) => has(f, 'mordedura_arana') || has(f, 'arana_peligrosa');
const herida = (f: Parameters<Rule['applies']>[0]) => anyOf(f, 'herida', 'herida_profunda', 'herida_sucia', 'herida_infectada', 'objeto_clavado');

export const COMMON_RULES: Rule[] = [
  // ── Alacrán (SSA 2026 y DGE 2012; la NOM-033-SSA2-2011 está cancelada: DOF 07-06-2024) ──────────────
  {
    id: 'SSA-ALAC-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => alacran(f) && possiblyAge(f, 0, years(5)),
    explicacion: { es: 'Niño menor de 5 años picado por alacrán: es el grupo con más muertes; necesita el antídoto aunque todavía no tenga síntomas.', nah: '' },
    accion: {
      es: `${CALL_911} Si en su comunidad hay un promotor capacitado con antídoto (suero antialacrán), avísele ya. Mantenga al niño tranquilo y quieto. Lave el piquete con agua y jabón y ponga algo frío envuelto en un trapo. ${NO_CORTAR}`,
      nah: '',
    },
    fuente: `${CITE.DGE_ALACRAN_2012}, p. 32 impresa / p. 33 del PDF: "más del 80 % de las defunciones… se presentan en menores de 5 años"; antídoto "en todo menor de cinco años… ya sea que presente, o no presente, síntomas"; ${CITE.SSA_IAVYS_2026}, p. 13 (menores de 5 años: antídoto "de forma inmediata" y traslado a segundo nivel)`,
    fuente_url: SRC.DGE_ALACRAN_2012,
    trigger: ['picadura_alacran'],
    needs: ['picadura_alacran', 'edad_meses'],
    // adaptado: la fuente indica antídoto inmediato; en Pahtli eso es traslado ya (la promotora no da antídoto).
    fidelidad: 'adaptado',
  },
  {
    id: 'SSA-ALAC-02',
    block: 'common',
    level: 'urgencia',
    applies: (f) =>
      alacran(f) &&
      anyOf(f, 'alacran_sintomas', 'babeo', 'no_traga_saliva', 'dificultad_respirar', 'vomito', 'vision_borrosa', 'dolor_pecho', 'distension_abdominal', 'convulsiones', 'sudor_frio', 'dificultad_hablar'),
    explicacion: { es: 'Picadura de alacrán con síntomas en todo el cuerpo (intoxicación moderada o grave): babeo, algo atorado en la garganta, ojos que se mueven solos, lengua que tiembla, sudor, falta de aire, vómito, vista borrosa o roja, dolor de pecho o panza inflada.', nah: '' },
    accion: {
      es: `${CALL_911} Si hay un promotor capacitado con antídoto (suero antialacrán), avísele ya. Mantenga a la persona tranquila y en reposo. ${NO_CORTAR}`,
      nah: '',
    },
    fuente: `${CITE.SSA_IAVYS_2026}, p. 10 (grado II: "sensación de cuerpo extraño o de obstrucción en la orofaringe y sialorrea, diaforesis, nistagmo, fasciculaciones linguales, disnea, distención abdominal"; grado III: "visión de halos rojos… vómitos… dolor retroesternal") y p. 6 ("se considera una urgencia médica")`,
    fuente_url: SRC.SSA_IAVYS_2026,
    trigger: ['picadura_alacran'],
    needs: ['picadura_alacran', 'alacran_sintomas'],
    fidelidad: 'adaptado',
  },
  {
    id: 'SSA-ALAC-03',
    block: 'common',
    level: 'urgencia',
    applies: (f) =>
      alacran(f) &&
      (knownAge(f, years(65)) || isPregnant(f) || anyOf(f, 'diabetes', 'hipertension', 'enfermedad_cronica', 'desnutricion')),
    explicacion: { es: 'Picadura de alacrán en persona de riesgo: mayor de 65 años, embarazada, o con diabetes, presión alta, asma, enfermedad del corazón o de los riñones, cirrosis o desnutrición.', nah: '' },
    accion: {
      es: `${CALL_911} Si hay un promotor capacitado con antídoto (suero antialacrán), avísele ya. Mantenga a la persona tranquila y en reposo. ${NO_CORTAR}`,
      nah: '',
    },
    fuente: `${CITE.SSA_IAVYS_2026}, p. 13 ("Mayores de 65 años, mujeres embarazadas y pacientes con cardiopatía, asma o insuficiencia renal, desnutrición, cirrosis, alcoholismo, diabetes, hipertensión arterial": antídoto "de forma inmediata" y traslado) y p. 29 (el promotor "canalizará al paciente a la unidad médica más cercana")`,
    fuente_url: SRC.SSA_IAVYS_2026,
    trigger: ['picadura_alacran'],
    needs: ['picadura_alacran', 'edad_meses', 'embarazada', 'diabetes', 'hipertension', 'enfermedad_cronica'],
    fidelidad: 'adaptado',
  },
  {
    id: 'SSA-ALAC-04',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => alacran(f),
    explicacion: { es: 'Picadura de alacrán: la Secretaría de Salud pide que la revise personal médico de la unidad más cercana y la observe por lo menos 2 horas.', nah: '' },
    accion: {
      es: `Llévelo AHORA a la unidad de salud para que lo revisen y lo observen. Si en el camino babea, siente algo en la garganta, le falta el aire, vomita o los ojos se le mueven solos: es URGENCIA. Lave el piquete con agua y jabón y ponga algo frío envuelto en un trapo. ${NO_CORTAR}`,
      nah: '',
    },
    fuente: `${CITE.SSA_IAVYS_2026}, p. 9 ("sea evaluada por un personal médico de la unidad de salud más cercana") y p. 10 (grado I: "Dolor local, parestesias… prurito nasal y faríngeo"); ${CITE.DGE_ALACRAN_2012}, p. 33 del PDF (observación "no menor a dos horas") y p. 38 del PDF (los síntomas aparecen "desde los primeros minutos hasta las dos horas")`,
    fuente_url: SRC.SSA_IAVYS_2026,
    trigger: ['picadura_alacran'],
    needs: ['picadura_alacran'],
    fidelidad: 'adaptado',
  },
  // ── Araña ─────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'SSA-ARANA-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => arana(f) && has(f, 'arana_peligrosa'),
    explicacion: { es: 'Mordedura de viuda negra (capulina) o de araña violinista (café, del rincón): urgencia médica.', nah: '' },
    accion: {
      es: `${CALL_911} Conserve la calma. Lave con agua y jabón y ponga hielo envuelto en un trapo; si es en brazo o pierna, súbalo arriba del corazón y que no se mueva de más. No use desinfectantes de color. Si se puede, lleve la araña en un frasco (con pinzas). ${NO_CORTAR}`,
      nah: '',
    },
    fuente: `${CITE.SSA_IAVYS_2026}, p. 6 (intoxicación por arácnidos "se considera una urgencia médica") y p. 20 (loxoscelismo "debe ser considerada una urgencia médica"); ${CITE.CENAPRECE_LOXO}, "Acciones en caso de ser picado", incisos a–j`,
    fuente_url: SRC.SSA_IAVYS_2026,
    trigger: ['mordedura_arana', 'arana_peligrosa'],
    needs: ['mordedura_arana', 'arana_peligrosa'],
    fidelidad: 'adaptado',
  },
  {
    id: 'SSA-ARANA-02',
    block: 'common',
    level: 'urgencia',
    applies: (f) => arana(f) && anyOf(f, 'arana_sintomas', 'dolor_pecho', 'dolor_abdominal_intenso', 'oliguria', 'dificultad_respirar', 'sudor_frio'),
    explicacion: { es: 'Mordedura de araña con síntomas de intoxicación: dolor que sube por el brazo o la pierna, calambres, panza dura, dolor de pecho, mucho sudor, mordida morada o negra, o casi no orina u orina oscura.', nah: '' },
    accion: {
      es: `${CALL_911} Conserve la calma, lave con agua y jabón, ponga hielo envuelto y que no se mueva de más. ${NO_CORTAR}`,
      nah: '',
    },
    fuente: `${CITE.SSA_IAVYS_2026}, p. 15 (latrodectismo: "el dolor se irradia a lo largo de la extremidad… dolor abdominal y/o torácico, contracturas musculares severas y diaforesis generalizada") y p. 19–20 (loxoscelismo: lesión "roja, blanca y azul", "vesícula hemorrágica"; forma sistémica; "urgencia médica")`,
    fuente_url: SRC.SSA_IAVYS_2026,
    trigger: ['mordedura_arana', 'arana_peligrosa'],
    needs: ['mordedura_arana', 'arana_sintomas'],
    fidelidad: 'adaptado',
  },
  {
    id: 'SSA-ARANA-03',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => arana(f),
    explicacion: { es: 'Mordedura de araña: la violinista puede no doler al principio y pasar desapercibida. Que la revisen hoy.', nah: '' },
    accion: {
      es: `Acuda lo más pronto posible a la unidad de salud. Mientras: conserve la calma, lave con agua y jabón, ponga hielo envuelto en un trapo y, si se puede, lleve la araña en un frasco. Si aparece dolor que sube por el brazo o la pierna, calambres, sudor, o la mordida se pone morada: URGENCIA. ${NO_CORTAR}`,
      nah: '',
    },
    fuente: `${CITE.CENAPRECE_LOXO}, inciso b): "acudir lo más pronto posible a la unidad de salud más cercana"; ${CITE.SSA_IAVYS_2026}, p. 19: la mordedura de Loxosceles "puede ser indolora y pasar desapercibida"`,
    fuente_url: SRC.CENAPRECE_LOXO,
    trigger: ['mordedura_arana', 'arana_peligrosa'],
    needs: ['mordedura_arana'],
    // adaptado: la indicación de CENAPRECE es para la violinista; se aplica a una araña desconocida porque no se puede descartar.
    fidelidad: 'adaptado',
  },
  // ── Reacción alérgica grave ──────────────────────────────────────────────────────────────────────
  {
    id: 'NHS-ANAPH-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => anyOf(f, 'hinchazon_labios_lengua', 'no_traga_saliva'),
    explicacion: { es: 'Se le hincharon de repente los labios, la lengua o la boca, o siente que se le cierra la garganta (posible reacción alérgica grave).', nah: '' },
    accion: { es: `${CALL_911} Si le cuesta respirar, déjela sentada en la posición en que respire mejor.`, nah: '' },
    fuente: `${CITE.NHS} Hives (revisada 26-04-2024) y Insect bites and stings (01-06-2023), "Call 999 if": "your lips, mouth, throat or tongue suddenly become swollen", "your throat feels tight or you're struggling to swallow"; ${CITE.NHS} Sore throat (08-04-2024), 999: "unable to swallow"`,
    fuente_url: SRC.NHS_HIVES,
    needs: ['hinchazon_labios_lengua', 'no_traga_saliva'],
    context: ['comezon', 'sarpullido'],
    // adaptado: el IITT pone la hinchazón de boca o garganta en amarillo; aquí se sigue la NHS (decisión provisional D8).
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-THROAT-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => (has(f, 'dolor_garganta') || has(f, 'hinchazon_boca_cuello')) && anyOf(f, 'babeo', 'no_puede_beber'),
    explicacion: { es: 'Dolor o hinchazón de garganta y no puede tragar o se le escurre la baba.', nah: '' },
    accion: { es: `${CALL_911} No le dé nada de comer. Déjela sentada.`, nah: '' },
    fuente: `${CITE.NHS} Sore throat (revisada 08-04-2024), "Call 999": "unable to swallow", "are drooling – this can be a sign of not being able to swallow"`,
    fuente_url: SRC.NHS_SORE_THROAT,
    trigger: ['dolor_garganta', 'hinchazon_boca_cuello'],
    needs: ['dolor_garganta', 'babeo', 'no_puede_beber'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-NECK-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => has(f, 'hinchazon_boca_cuello'),
    explicacion: { es: 'Hinchazón o bola en la boca, la encía, la quijada, la garganta o el cuello.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud (o al dentista, si es por una muela). Si no puede tragar, babea o le cuesta respirar: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT}, criterio amarillo "Any swelling/mass of mouth, throat or neck" (tablas ≥12 y <12 años)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['hinchazon_boca_cuello'],
    context: ['dolor_muela', 'dolor_garganta'],
    // adaptado: se incluye la encía, la quijada y el cachete (hinchazón por muela), que el IITT no nombra.
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-TOOTH-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'dolor_muela') && anyOf(f, 'hinchazon_cuello_ojo', 'no_traga_saliva', 'dificultad_respirar', 'dificultad_hablar'),
    explicacion: { es: 'Dolor de muela con hinchazón alrededor del ojo o del cuello, o que no lo deja respirar, tragar o hablar.', nah: '' },
    accion: { es: `${CALL_911} Que no maneje: que alguien lo lleve.`, nah: '' },
    fuente: `${CITE.NHS} Toothache (revisada 01-07-2024): "Go to A&E if you have toothache and: the area around your eye or your neck is swollen; swelling in your mouth or neck is making it difficult for you to breathe, swallow or speak"`,
    fuente_url: SRC.NHS_TOOTHACHE,
    trigger: ['dolor_muela'],
    needs: ['dolor_muela', 'hinchazon_cuello_ojo', 'no_traga_saliva'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMSS062-FARINGO-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => possiblyAge(f, 3, years(18)) && has(f, 'placas_garganta') && hasFever(f),
    explicacion: { es: 'Calentura con placas blancas o pus en la garganta (posible infección por bacteria que necesita antibiótico con receta).', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud: puede necesitar antibiótico que da el médico. Si no puede tragar, babea o le cuesta respirar: URGENCIA.', nah: '' },
    fuente: `${CITE.IMSS_062}, p. 4 (sospecha de faringoamigdalitis estreptocócica: "Fiebre", "Exudado amigdalino", "Adenopatía anterior dolorosa", "Ausencia de tos") y p. 6 ("Otorgar tratamiento antimicrobiano inmediato: Faringoamigdalitis aguda estreptocócica")`,
    fuente_url: SRC.IMSS_062,
    trigger: ['placas_garganta'],
    needs: ['placas_garganta', 'fiebre', 'edad_meses'],
    context: ['dolor_garganta'],
    // adaptado: no se exige "ausencia de tos" (sería una pregunta donde "No" sube el nivel); más protector.
    fidelidad: 'adaptado',
  },
  // ── Oído ─────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'IMCI-EAR-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, 2, years(5)) && has(f, 'hinchazon_detras_oreja'),
    explicacion: { es: 'Niño con hinchazón dolorosa detrás de la oreja (posible mastoiditis).', nah: '' },
    accion: { es: 'Referir URGENTE al hospital: conseguir transporte o llamar al 911 ahora.', nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 9 del PDF, "Does the child have an ear problem?": "Tender swelling behind the ear" → MASTOIDITIS (rosa), "Refer URGENTLY to hospital"`,
    fuente_url: SRC.IMCI_2014,
    trigger: ['hinchazon_detras_oreja'],
    needs: ['hinchazon_detras_oreja', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMCI-EAR-02',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => (knownAge(f, 2, years(5)) && anyOf(f, 'dolor_oido', 'pus_oido')) || (knownAge(f, years(5), years(18)) && has(f, 'pus_oido')),
    explicacion: { es: 'Niño menor de 5 años con dolor de oído o pus en el oído, o niño o adolescente con pus en el oído (infección de oído que trata el centro de salud).', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud: puede necesitar antibiótico que da el médico. No le meta nada al oído (ni cotonetes, ni gotas caseras, ni aceite).', nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 9 del PDF: "Pus is seen draining from the ear… or Ear pain" → ACUTE EAR INFECTION (amarillo: antibiótico); ${CITE.IMSS_062}, p. 6: "Otorgar tratamiento antimicrobiano inmediato… Otitis media aguda en niños con otorrea"`,
    fuente_url: SRC.IMCI_2014,
    trigger: ['dolor_oido', 'pus_oido'],
    needs: ['dolor_oido', 'pus_oido', 'edad_meses'],
    // adaptado: amarillo de AIEPI → centro_hoy (la promotora no da antibiótico); con IMSS-062 se extiende el pus en el oído hasta los 18 años.
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-EAR-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) =>
      possiblyAge(f, years(5)) &&
      (anyOf(f, 'pus_oido', 'hinchazon_detras_oreja', 'objeto_en_oido') || (has(f, 'dolor_oido') && isNum(f.duracion_dias) && f.duracion_dias >= 3)),
    explicacion: { es: 'Le sale pus o líquido del oído, tiene hinchazón alrededor de la oreja, algo atorado en el oído, o el dolor de oído lleva 3 días o más.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. No le meta nada al oído (ni cotonetes, ni gotas caseras, ni aceite) y no intente sacar lo que esté atorado.', nah: '' },
    fuente: `${CITE.NHS} Earache (revisada 27-10-2025), "urgent GP appointment or NHS 111 if": "have had it for more than 2 to 3 days", "have swelling around the ear", "have fluid coming from the ear", "have something stuck in the ear"`,
    fuente_url: SRC.NHS_EARACHE,
    // duracion_dias no va en `needs`: una duración conocida no es evidencia de un problema de oído.
    trigger: ['pus_oido', 'hinchazon_detras_oreja', 'objeto_en_oido'],
    needs: ['pus_oido', 'hinchazon_detras_oreja', 'objeto_en_oido', 'edad_meses'],
    context: ['dolor_oido'],
    fidelidad: 'adaptado',
  },
  // ── Panza ────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'NHS-ABD-OBST-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'no_obra_ni_gases'),
    explicacion: { es: 'No puede hacer del baño ni echar gases (posible obstrucción del intestino).', nah: '' },
    accion: { es: `${CALL_911} No le dé de comer ni medicinas para el dolor o laxantes mientras la valoran.`, nah: '' },
    fuente: `${CITE.NHS} Stomach ache (revisada 26-05-2023), "Call 999 or go to A&E if": "you cannot poo or fart"; ${CITE.IMSS_031}, p. 7: en el adulto mayor con sospecha de "obstrucción intestinal… enviar a urgencias"`,
    fuente_url: SRC.NHS_STOMACH,
    needs: ['no_obra_ni_gases'],
    context: ['estrenimiento', 'gases', 'distension_abdominal'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMSS031-APEND-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'dolor_derecha_baja') && (anyOf(f, 'dolor_al_moverse', 'vomito', 'nauseas') || hasFever(f)),
    explicacion: { es: 'Dolor de panza abajo a la derecha (o que empezó en el ombligo y se pasó a la derecha) con dolor al caminar o toser, náusea, vómito o calentura: posible apendicitis.', nah: '' },
    accion: { es: `${CALL_911} No le dé de comer, ni laxantes, ni medicinas para el dolor: pueden esconder la apendicitis.`, nah: '' },
    fuente: `${CITE.IMSS_031}, p. 2 (el dolor periumbilical "antes de 24 horas migra a cuadrante inferior derecho… náusea y vómitos… fiebre de 38° C o más. El dolor se incrementa al caminar y al toser") y p. 7 ("debe ser referido de medicina familiar a urgencias… en forma inmediata")`,
    fuente_url: SRC.IMSS_031,
    trigger: ['dolor_derecha_baja'],
    needs: ['dolor_derecha_baja', 'dolor_al_moverse', 'vomito', 'fiebre'],
    context: ['dolor_abdominal'],
    // adaptado: la GPC pide además la exploración (irritación peritoneal), que la promotora no hace.
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-VOM-GREEN-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, years(12)) && has(f, 'vomito_verde'),
    explicacion: { es: 'Adulto o adolescente que vomita verde.', nah: '' },
    accion: { es: `${CALL_911} Que tome solo traguitos de agua si los tolera.`, nah: '' },
    fuente: `${CITE.NHS} Diarrhoea and vomiting (revisada 21-12-2023), "Call 999 if": "have green vomit (adults)"`,
    fuente_url: SRC.NHS_DIARRHOEA_VOMITING,
    trigger: ['vomito_verde'],
    needs: ['vomito_verde', 'edad_meses'],
    // adaptado: la NHS dice "adultos"; se aplica desde los 12 años (el corte de adulto del IITT).
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-DM-VOM-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'diabetes') && anyOf(f, 'vomito', 'vomita_todo', 'vomito_persistente') && has(f, 'dolor_abdominal'),
    explicacion: { es: 'Persona con diabetes que tiene dolor de panza y está vomitando.', nah: '' },
    accion: { es: `${CALL_911} Lleve sus medicinas o la insulina que usa.`, nah: '' },
    fuente: `${CITE.NHS} Stomach ache (revisada 26-05-2023), "Call 999 or go to A&E if" (con dolor de panza): "you have diabetes and you're vomiting"`,
    fuente_url: SRC.NHS_STOMACH,
    trigger: ['diabetes'],
    needs: ['diabetes', 'vomito', 'dolor_abdominal'],
    context: ['diabetes'],
    // Decisión provisional D4 (docs/decisiones-clinicas.md): urgencia, literal de la NHS; no hay fuente mexicana leída.
    fidelidad: 'verbatim',
  },
  {
    id: 'NHS-BLOAT-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => possiblyAge(f, years(12)) && has(f, 'distension_abdominal') && anyOf(f, 'vomito', 'diarrea', 'estrenimiento', 'dolor_abdominal'),
    explicacion: { es: 'Panza hinchada o inflada con dolor de panza, vómito, diarrea o estreñimiento.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Si el dolor es repentino y muy fuerte, vomita sangre o no puede hacer del baño ni echar gases: URGENCIA.', nah: '' },
    fuente: `${CITE.NHS} Bloating (revisada 21-01-2026), "Ask for an urgent GP appointment or get help from NHS 111 if": "you have bloating with vomiting (being sick), diarrhoea or constipation", "you have bloating with a stomach ache"`,
    fuente_url: SRC.NHS_BLOATING,
    trigger: ['distension_abdominal'],
    needs: ['distension_abdominal', 'vomito', 'diarrea', 'estrenimiento', 'dolor_abdominal', 'edad_meses'],
    // adaptado: "bloating" se toma como panza hinchada o inflada (no los gases solos).
    fidelidad: 'adaptado',
  },
  {
    id: 'IITT-R-TESTIS-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => f.sexo !== 'F' && possiblyAge(f, 0, years(12)) && has(f, 'dolor_testiculo'),
    explicacion: { es: 'Niño menor de 12 años con dolor o hinchazón repentina de un testículo.', nah: '' },
    accion: { es: `${CALL_911} El tiempo cuenta para salvar el testículo. No le dé de comer.`, nah: '' },
    fuente: `${CITE.IITT} pediátrico (<12 años), criterio rojo "Acute testicular/scrotal pain or priapism"`,
    fuente_url: SRC.IITT_PED,
    trigger: ['dolor_testiculo'],
    needs: ['dolor_testiculo', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-TESTIS-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => f.sexo !== 'F' && possiblyAge(f, years(12)) && has(f, 'dolor_testiculo'),
    explicacion: { es: 'Adolescente o adulto con dolor repentino de un testículo.', nah: '' },
    accion: { es: 'Llevar HOY, lo antes posible, a la unidad de salud. Si el dolor es muy fuerte y de repente, con vómito: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT} (≥12 años), criterio amarillo "Acute testicular/scrotal pain or priapism"`,
    fuente_url: SRC.IITT_ADULT,
    trigger: ['dolor_testiculo'],
    needs: ['dolor_testiculo', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  // ── Orina ────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'IMSS077-PIELO-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => has(f, 'ardor_orinar') && (hasFever(f) || has(f, 'dolor_fosa_renal')),
    explicacion: { es: 'Ardor al orinar con calentura o con dolor en la espalda de un lado, debajo de las costillas (posible infección del riñón).', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud: necesita tratamiento que da el médico. Si está confundida, muy dormida o vomita todo: URGENCIA.', nah: '' },
    fuente: `${CITE.IMSS_077}, p. 3 (infección urinaria alta: "dolor en fosa renal y fiebre mayor de 38°C… náuseas, vómito, escalofrío") y p. 6 ("Si el paciente tiene síntomas de afección sistémica enviar a hospital"); ${CITE.NHS} UTIs (revisada 11-07-2025), urgente: "pain in the lower tummy or in the back, just under the ribs", "very high or low temperature"`,
    fuente_url: SRC.IMSS_077,
    trigger: ['ardor_orinar'],
    needs: ['ardor_orinar', 'fiebre', 'dolor_fosa_renal'],
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-UTI-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) =>
      has(f, 'ardor_orinar') &&
      (f.sexo === 'M' || knownAge(f, 0, years(16)) || knownAge(f, years(65)) || anyOf(f, 'diabetes', 'orina_sangre')),
    explicacion: { es: 'Ardor al orinar en hombre, en menor de 16 años, en mayor de 65, en persona con diabetes, o con sangre en la orina.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud: necesita que lo revise el médico. Tome suficientes líquidos.', nah: '' },
    fuente: `${CITE.NHS} UTIs (revisada 11-07-2025), "Ask for an urgent GP appointment or get help from NHS 111 if": "you're aged 65 or older", "your child is aged 15 or younger", "you're a man", "you have diabetes", "you have blood in your pee"`,
    fuente_url: SRC.NHS_UTI,
    trigger: ['ardor_orinar'],
    needs: ['ardor_orinar', 'sexo', 'edad_meses', 'orina_sangre', 'diabetes'],
    fidelidad: 'verbatim',
  },
  // ── Espalda ──────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'IMSS045-CAUDA-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'dolor_espalda_baja') && anyOf(f, 'cauda_equina', 'no_puede_orinar'),
    explicacion: { es: 'Dolor de espalda con dificultad para orinar, sin control de la orina o la popó, entrepierna dormida o debilidad de las dos piernas.', nah: '' },
    accion: { es: `${CALL_911} Que se mueva lo menos posible.`, nah: '' },
    fuente: `${CITE.IMSS_045}, p. 6 ("La retención urinaria… y la anestesia en silla de montar, son los signos de mayor utilidad en el diagnóstico de la cauda equina"; "dolor en ambas piernas, déficit sensitivo-motor"); ${CITE.NHS} Back pain (revisada 05-03-2026), "Call 999 or go to A&E": "weakness or numbness in both legs", "loss of feeling around your genitals or anus", "difficulty peeing, or peeing or pooing yourself"`,
    fuente_url: SRC.IMSS_045,
    trigger: ['dolor_espalda_baja'],
    needs: ['dolor_espalda_baja', 'cauda_equina', 'no_puede_orinar'],
    fidelidad: 'adaptado',
  },
  {
    id: 'IMSS045-FIEBRE-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => has(f, 'dolor_espalda_baja') && hasFever(f),
    explicacion: { es: 'Dolor de espalda con calentura.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Si además arde al orinar o duele de un lado bajo las costillas, dígalo en la unidad.', nah: '' },
    fuente: `${CITE.IMSS_045}, p. 4 (signos de alarma en lumbalgia: "fiebre"); ${CITE.NHS} Back pain (revisada 05-03-2026), urgente: "you feel hot, cold, shivery or generally unwell"`,
    fuente_url: SRC.IMSS_045,
    trigger: ['dolor_espalda_baja'],
    needs: ['dolor_espalda_baja', 'fiebre'],
    fidelidad: 'adaptado',
  },
  // ── Piel ─────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'IITT-Y-RASH-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => has(f, 'erupcion_empeora'),
    explicacion: { es: 'Ronchas o erupción nueva que se extiende en horas, o la piel se está pelando.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Si se le hinchan los labios o la lengua o le cuesta respirar: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT}, criterio amarillo "New rash worsening over hours or peeling (no red criteria)" (tablas ≥12 y <12 años); ${CITE.NHS} Hives (revisada 26-04-2024), urgente: "the rash is spreading"`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['erupcion_empeora'],
    context: ['sarpullido', 'comezon'],
    fidelidad: 'verbatim',
  },
  // ── Heridas ──────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'NHS-WOUND-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => anyOf(f, 'objeto_clavado', 'herida_profunda') || (herida(f) && has(f, 'herida_sin_sensibilidad')),
    explicacion: { es: 'Herida muy grande o profunda, con algo clavado, o que deja sin sentir o sin mover la parte de abajo.', nah: '' },
    accion: { es: `${CALL_911} Apriete alrededor con un trapo limpio para parar la sangre. NO saque lo que esté clavado. Si es en brazo o pierna, súbalo más arriba del corazón.`, nah: '' },
    fuente: `${CITE.NHS} Cuts and grazes (revisada 02-04-2026), "Call 999 or go to A&E if": "you lose feeling near the wound or have trouble moving it", "the wound is very large or deep", "there's something stuck in the cut… do not try to take it out yourself"`,
    fuente_url: SRC.NHS_CUTS,
    trigger: ['objeto_clavado', 'herida_profunda', 'herida_sin_sensibilidad'],
    needs: ['objeto_clavado', 'herida_profunda', 'herida_sin_sensibilidad'],
    context: ['herida'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NHS-WOUND-02',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => has(f, 'herida_sucia') || has(f, 'herida_infectada') || (herida(f) && hasFever(f)),
    explicacion: { es: 'Herida grande (más de 5 cm), sucia con tierra o por clavo, o con señas de infección (roja, caliente, hinchada, con pus) o con calentura.', nah: '' },
    accion: { es: 'Lave bien la herida con agua limpia y tápela con un trapo o gasa limpia. Llevar HOY a la unidad de salud: puede necesitar curación y vacuna contra el tétanos (lleve la cartilla).', nah: '' },
    fuente: `${CITE.NHS} Cuts and grazes (revisada 02-04-2026), "Ask for an urgent GP appointment or get help from NHS 111 if": "a wound has soil, pus or body fluids in it, or it's still dirty after cleaning it", "a cut is swollen, red and getting more painful or pus is coming out of it", "a cut is larger than around 5cm", "feel generally unwell or have a high temperature"`,
    fuente_url: SRC.NHS_CUTS,
    trigger: ['herida_sucia', 'herida_infectada'],
    needs: ['herida_sucia', 'herida_infectada', 'fiebre'],
    context: ['herida'],
    // adaptado: se agrega "por clavo" (herida punzante, sucia por definición) y la cartilla de vacunación.
    fidelidad: 'adaptado',
  },
  // ── Quemaduras ───────────────────────────────────────────────────────────────────────────────────
  {
    id: 'IITT-R-BURN-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'quemadura_grave') || (has(f, 'quemadura') && (knownAge(f, 0, years(2)) || knownAge(f, years(70) + 1))),
    explicacion: { es: 'Quemadura grave: en la cara o el cuello, que le da toda la vuelta a un brazo, pierna o al cuerpo, respiró humo, o es un niño menor de 2 años o una persona mayor de 70.', nah: '' },
    accion: { es: `${CALL_911} Enfríe con agua de la llave (no hielo) solo si la quemadura es pequeña; si es grande, tápela con una sábana o trapo limpio y abríguela para que no se enfríe. No ponga pomadas, aceite, pasta de dientes ni remedios. No reviente las ampollas.`, nah: '' },
    fuente: `${CITE.IITT}, tarjeta de referencia "High-risk trauma" (quemaduras de espesor parcial o total): "Circumferential or involving face or neck", "Inhalation injury", "Any burn in age < 2 or age > 70"; ${CITE.IMSS_040}, p. 2 ("Todo paciente con quemaduras respiratorias o por inhalación de humo"); ${CITE.WHO_BURNS_FS} ("Do not apply ice", "Avoid prolonged cooling", "Wrap the patient in a clean cloth")`,
    fuente_url: SRC.IITT_REFCARD,
    trigger: ['quemadura', 'quemadura_grave'],
    needs: ['quemadura_grave', 'quemadura', 'edad_meses'],
    // adaptado: no se usa el criterio ">15 % de la superficie" (no hay forma verificada de explicárselo a la promotora).
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-BURN-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'quemadura_quimica_electrica'),
    explicacion: { es: 'Quemadura por ácido, químico o electricidad, o en sus partes o las nalgas.', nah: '' },
    accion: { es: `${CALL_911} Si fue por electricidad: no lo toque hasta que esté cortada la luz. Si fue por químico: enjuague con mucha agua. No ponga pomadas ni remedios.`, nah: '' },
    fuente: `${CITE.NHS} Burns and scalds (revisada 31-03-2026), "Call 999 or go to A&E": "is on your face, genitals or bottom", "has been caused by an acid or chemical, or by electricity"; ${CITE.IMSS_040}, p. 2 ("Todo paciente con quemaduras eléctricas por alta tensión"); ${CITE.WHO_BURNS_FS} (químicos: enjuagar con mucha agua)`,
    fuente_url: SRC.NHS_BURNS,
    needs: ['quemadura_quimica_electrica'],
    context: ['quemadura'],
    fidelidad: 'verbatim',
  },
  // ── Golpe en la cabeza ───────────────────────────────────────────────────────────────────────────
  {
    id: 'NHS-HEAD-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) =>
      has(f, 'golpe_cabeza') &&
      (anyOf(f, 'inconsciente', 'letargico', 'convulsiones', 'vision_borrosa', 'pus_oido', 'sangre_oido', 'debilidad_un_lado', 'confusion', 'dificultad_hablar', 'perdida_equilibrio', 'dolor_cabeza', 'anticoagulante') ||
        knownAge(f, 0, 12)),
    explicacion: { es: 'Golpe en la cabeza con señas de peligro: no despierta o no se mantiene despierto, convulsión, ve o escucha mal, sale líquido o sangre del oído, debilidad, confusión, dolor de cabeza, toma medicina para adelgazar la sangre, o es un bebé menor de 1 año.', nah: '' },
    accion: { es: `${CALL_911} No mueva el cuello si cayó de altura. Si no despierta, acuéstelo de lado.`, nah: '' },
    fuente: `${CITE.NHS} Head injury and concussion (revisada 29-05-2025), "Call 999 if someone has hit their head and": "cannot stay awake", "has a fit (seizure)", "problems with their vision or hearing", "clear fluid coming from their ears or nose", "bleeding from their ears", "new numbness or weakness", "a bruise, swelling or large cut on their head and they are under 1 year old"; ${CITE.NHS} Headaches (revisada 17-04-2024), 999: "has had a head injury within the last 3 months"; ${CITE.IITT}, tarjeta "High-risk trauma": "Patient with bleeding disorder or on anticoagulation"`,
    fuente_url: SRC.NHS_HEAD_INJURY,
    trigger: ['golpe_cabeza'],
    needs: ['golpe_cabeza', 'letargico', 'vision_borrosa', 'dolor_cabeza', 'anticoagulante', 'pus_oido', 'edad_meses'],
    // Decisión provisional D11: anticoagulante con golpe → urgencia (IITT), no centro_hoy (NHS 111).
    fidelidad: 'adaptado',
  },
  {
    id: 'NHS-HEAD-02',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => has(f, 'golpe_cabeza') && anyOf(f, 'vomito', 'mareo'),
    explicacion: { es: 'Golpe en la cabeza y después vomitó o anda mareado.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Un adulto debe quedarse con la persona. Si no se mantiene despierta, convulsiona o le sale líquido del oído: URGENCIA.', nah: '' },
    fuente: `${CITE.NHS} Head injury and concussion (revisada 29-05-2025), "Get help from NHS 111 if you or someone else recently had a head injury and": "are being sick (vomiting)", "feel dizzy"`,
    fuente_url: SRC.NHS_HEAD_INJURY,
    trigger: ['golpe_cabeza'],
    needs: ['golpe_cabeza', 'vomito', 'mareo'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-R-TRAUMA-ANTICOAG-01',
    block: 'common',
    level: 'urgencia',
    applies: (f) => has(f, 'anticoagulante') && anyOf(f, 'golpe_caida', 'fractura', 'herida', 'herida_profunda'),
    explicacion: { es: 'Golpe, caída o herida en una persona que toma medicina para adelgazar la sangre (trauma de alto riesgo).', nah: '' },
    accion: { es: `${CALL_911} Apriete las heridas que sangren. Lleve la medicina que toma.`, nah: '' },
    fuente: `${CITE.IITT}, tarjeta de referencia "High-risk trauma": "Patient with bleeding disorder or on anticoagulation"`,
    fuente_url: SRC.IITT_REFCARD,
    trigger: ['anticoagulante'],
    needs: ['anticoagulante', 'golpe_caida', 'herida'],
    fidelidad: 'verbatim',
  },
  // ── Dolor de cabeza ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'NHS-HA-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => anyOf(f, 'dolor_cabeza', 'dolor_cabeza_intenso') && anyOf(f, 'vomito', 'vomito_persistente', 'vomita_todo'),
    explicacion: { es: 'Dolor de cabeza con vómito.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Si el dolor empezó de repente y es muy fuerte, tiene el cuello tieso, se confunde o tuvo un golpe en la cabeza: URGENCIA.', nah: '' },
    fuente: `${CITE.NHS} Headaches (revisada 17-04-2024), "NHS 111 or urgent GP appointment if": "you or a child has a headache and is being sick (vomiting)"`,
    fuente_url: SRC.NHS_HEADACHES,
    trigger: ['dolor_cabeza'],
    needs: ['dolor_cabeza', 'vomito'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-HEAD-PED-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => knownAge(f, years(2), years(12)) && anyOf(f, 'dolor_cabeza', 'dolor_cabeza_intenso'),
    explicacion: { es: 'Niño de 2 a 11 años con dolor de cabeza.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud para que lo revisen. Si tiene el cuello tieso, mucho sueño, convulsiones o vomita todo: URGENCIA.', nah: '' },
    fuente: `${CITE.IITT} pediátrico (<12 años), criterio amarillo "Headache (no red criteria)"`,
    fuente_url: SRC.IITT_PED,
    trigger: ['dolor_cabeza'],
    needs: ['dolor_cabeza', 'edad_meses'],
    // adaptado: desde los 2 años (antes no se puede saber si "le duele la cabeza"); el IITT no pone edad mínima.
    fidelidad: 'adaptado',
  },
  // ── Tos ──────────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'NHS-COUGH-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => has(f, 'tos_sangre'),
    explicacion: { es: 'Tose o escupe sangre.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Si es mucha sangre o le falta el aire: URGENCIA.', nah: '' },
    fuente: `${CITE.NHS} Cough (revisada 08-12-2023), "Ask for an urgent GP appointment or get help from NHS 111 if": "you're coughing up blood"; ${CITE.NOM_006}, 3.15 (caso probable de tuberculosis: "tos con expectoración o hemoptisis")`,
    fuente_url: SRC.NHS_COUGH,
    needs: ['tos_sangre'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NOM006-TB-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) => knownAge(f, years(5)) && has(f, 'tos') && isNum(f.duracion_dias) && f.duracion_dias >= 14,
    explicacion: { es: 'Tos de 2 semanas o más (5 años o más): hay que descartar tuberculosis.', nah: '' },
    accion: { es: 'Llevar a la unidad de salud lo antes posible para estudiar la tos (muestra de flema). Que tape la tos con el brazo.', nah: '' },
    fuente: `${CITE.NOM_006}, 3.15 "Caso probable de tuberculosis pulmonar": "tos con expectoración o hemoptisis, de dos o más semanas de evolución"; en niñas y niños "tos con o sin expectoración durante dos o más semanas"`,
    fuente_url: SRC.NOM_006,
    trigger: ['tos'],
    needs: ['tos', 'edad_meses'],
    // Decisión provisional D5: la NOM define el caso a estudiar, no la urgencia; se usa centro_hoy como IMCI-RESP-04 (<5 años).
    fidelidad: 'adaptado',
  },
  // ── Diabetes: azúcar baja ────────────────────────────────────────────────────────────────────────
  {
    id: 'NOM015-HIPO-01',
    block: 'common',
    level: 'centro_hoy',
    applies: (f) =>
      has(f, 'azucar_baja') ||
      (has(f, 'diabetes') && anyOf(f, 'sintomas_hipoglucemia', 'sudor_frio', 'mareo', 'mareo_al_pararse', 'vision_borrosa', 'debilidad_general', 'nervios_ansiedad')),
    explicacion: { es: 'Posible azúcar baja (hipoglucemia): persona con diabetes con sudor frío, temblor, mucha hambre, corazón acelerado, nervios, mareo, vista borrosa o debilidad.', nah: '' },
    accion: {
      es: 'Si está despierta y puede tragar: déle YA algo dulce de tomar (un vaso chico de jugo de fruta o refresco normal, no de dieta) y, cuando mejore, algo de comer (pan o tortilla). Si en 10 a 15 minutos no mejora, déle otra vez algo dulce y llévela de URGENCIA. Si no despierta o convulsiona: no le dé nada por la boca, acuéstela de lado y llame al 911. Aunque mejore, que la revisen HOY en la unidad de salud.',
      nah: '',
    },
    fuente: `${CITE.NOM_015}, 3.41 (hipoglucemia: "sudoración fría, temblor, hambre, palpitaciones y ansiedad… visión borrosa, debilidad, mareos"), 11.11.8.4 (consciente: "carbohidratos líquidos… seguidos de carbohidratos de absorción más lenta, pudiendo llegar a ser necesario repetir") y 11.11.8.5 (pérdida del estado de alerta: "llevar con urgencia al paciente al segundo nivel"; "cabeza volteada hacia un lado"); ${CITE.NHS} Low blood sugar (revisada 03-08-2023): "a small glass of fruit juice or sugary fizzy drink", "after 10 to 15 minutes", inconsciente: "Do not give them any food or drink"`,
    fuente_url: SRC.NOM_015,
    trigger: ['diabetes', 'azucar_baja'],
    needs: ['azucar_baja', 'diabetes', 'sintomas_hipoglucemia', 'sudor_frio', 'mareo'],
    context: ['diabetes'],
    // adaptado: la NOM no fija el nivel; el IITT pone "Hypoglycaemia" en rojo. Se sigue la NOM (consciente → algo dulce
    // y valoración; sin alerta → urgencia, que ya dan GEN-UNC-01 y GEN-CONV-01). Pendiente de la Dra. Ines.
    fidelidad: 'adaptado',
  },
];
