import type { Rule } from './types';
import { anyOf, has, isPostpartum, isPregnant, knownAge, possiblyAge, years } from './helpers';
import { CITE, SRC } from './sources';
import { SCREENING_KEY } from '../screening';

const REFER_NOW =
  'Referir URGENTE al hospital: conseguir transporte o llamar al 911 ahora. No esperar. Acompañar al paciente.';

/**
 * Signos generales de peligro. Los que aplican a cualquier edad (convulsiones, no responde,
 * estridor, cianosis, sangrado abundante) se respaldan en AIEPI para <5 años y en el IITT para el resto.
 */
export const GENERAL_DANGER_RULES: Rule[] = [
  {
    id: 'GEN-CONV-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => has(f, 'convulsiones'),
    explicacion: { es: 'Ha tenido convulsiones (ataques). Es un signo general de peligro.', nah: '' },
    accion: {
      es: `${REFER_NOW} Si está convulsionando: acostarlo de lado, no meter nada en la boca, retirar objetos con los que se pueda golpear.`,
      nah: '',
    },
    fuente: `${CITE.IMCI_2014}, p. 5 del PDF "Check for general danger signs" (2 meses a 5 años: convulsiones en esta enfermedad); ${CITE.ICCM}, p. 6 "Danger signs"; ${CITE.IITT} (≥12 años: rojo solo "Active convulsions")`,
    fuente_url: SRC.IMCI_2014,
    needs: ['convulsiones'],
    // adaptado: para ≥5 años el IITT solo pone en rojo la convulsión ACTIVA; aquí cualquier convulsión reciente es urgencia (sobre-triaje aceptado).
    fidelidad: 'adaptado',
  },
  {
    id: 'GEN-UNC-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => has(f, 'inconsciente'),
    explicacion: { es: 'Está inconsciente o no responde. Es un signo general de peligro.', nah: '' },
    accion: { es: `${REFER_NOW} Acostarlo de lado y vigilar que respire.`, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 5 del PDF ("lethargic or unconscious"); ${CITE.IITT}, criterio rojo "Unresponsive"`,
    fuente_url: SRC.IMCI_2014,
    needs: ['inconsciente'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMCI-GDS-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, 2, 60) && has(f, 'letargico'),
    explicacion: { es: 'Niño de 2 meses a 5 años anormalmente dormido o difícil de despertar (letárgico).', nah: '' },
    accion: { es: `${REFER_NOW} Mantenerlo abrigado. Si puede beber, seguir dándole pecho o líquidos en el camino.`, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 5 del PDF, "Any general danger sign → VERY SEVERE DISEASE, refer URGENTLY"; ${CITE.ICCM}, p. 6 ("Unusually sleepy or unconscious")`,
    fuente_url: SRC.IMCI_2014,
    needs: ['letargico', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMCI-GDS-02',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, 2, 60) && has(f, 'no_puede_beber'),
    explicacion: { es: 'Niño de 2 meses a 5 años que no puede beber ni mamar.', nah: '' },
    accion: { es: `${REFER_NOW} Mantenerlo abrigado.`, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 5 del PDF ("Is the child able to drink or breastfeed?"); ${CITE.ICCM}, p. 6 ("Not able to drink or feed anything")`,
    fuente_url: SRC.IMCI_2014,
    needs: ['no_puede_beber', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMCI-GDS-03',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, 2, 60) && has(f, 'vomita_todo'),
    explicacion: { es: 'Niño de 2 meses a 5 años que vomita todo lo que come o bebe.', nah: '' },
    accion: { es: `${REFER_NOW} Ofrecer sorbos pequeños y frecuentes de Vida Suero Oral en el camino si los tolera.`, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 5 del PDF ("Does the child vomit everything?"); ${CITE.ICCM}, p. 6 ("Vomits everything")`,
    fuente_url: SRC.IMCI_2014,
    needs: ['vomita_todo', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'GEN-STRIDOR-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => has(f, 'estridor'),
    explicacion: { es: 'Estridor: ruido áspero al jalar aire estando tranquilo. La vía aérea puede estar obstruida.', nah: '' },
    accion: { es: `${REFER_NOW} Mantenerlo tranquilo y sentado como esté más cómodo; no forzarlo a acostarse.`, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 6 del PDF ("Stridor in calm child → SEVERE PNEUMONIA OR VERY SEVERE DISEASE, refer URGENTLY"); ${CITE.IITT}, criterio rojo "Stridor"`,
    fuente_url: SRC.IMCI_2014,
    needs: ['estridor'],
    context: ['tos', 'dificultad_respirar', 'respira_rapido'],
    fidelidad: 'verbatim',
  },
  {
    id: 'GEN-CYAN-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => anyOf(f, 'cianosis', 'apnea'),
    explicacion: { es: 'Se pone morado (cianosis) o deja de respirar por momentos.', nah: '' },
    accion: { es: `${REFER_NOW} Vigilar la respiración durante el traslado.`, nah: '' },
    fuente: `${CITE.NOM_031}, num. 8.2.3 (neumonía con dificultad respiratoria grave: "tiraje, cianosis") y 8.2.5.3.1.1 ("Envío inmediato a un hospital"); ${CITE.IITT}, rojo "central cyanosis"; ${CITE.NOM_007}, num. 5.6.1.9 (apnea y cianosis del recién nacido)`,
    fuente_url: SRC.NOM_031,
    needs: ['cianosis', 'apnea'],
    context: ['tos', 'dificultad_respirar', 'respira_rapido'],
    fidelidad: 'verbatim',
  },
  {
    id: 'GEN-BLEED-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => has(f, 'sangrado_abundante'),
    explicacion: { es: 'Sangrado abundante (hemorragia).', nah: '' },
    accion: { es: `${REFER_NOW} Si es una herida: apretar fuerte con un trapo limpio sin soltar.`, nah: '' },
    fuente: `${CITE.IITT}, criterio rojo "Heavy bleeding" (tabla adulto y pediátrica)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['sangrado_abundante'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMCI-ANEM-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, 2, 60) && has(f, 'palidez_intensa'),
    explicacion: { es: 'Niño de 2 meses a 5 años con palidez intensa de las palmas (posible anemia grave).', nah: '' },
    accion: { es: REFER_NOW, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 11 del PDF, "Severe palmar pallor → SEVERE ANAEMIA, refer URGENTLY"`,
    fuente_url: SRC.IMCI_2014,
    needs: ['palidez_intensa', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMCI-ANEM-02',
    block: 'general_danger',
    level: 'centro_hoy',
    applies: (f) => possiblyAge(f, 2, 60) && has(f, 'palidez'),
    explicacion: { es: 'Niño de 2 meses a 5 años con algo de palidez en las palmas (posible anemia).', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud para valoración y tratamiento de la anemia.', nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 11 del PDF, "Some pallor → ANAEMIA (give iron, follow-up 14 days)"`,
    fuente_url: SRC.IMCI_2014,
    needs: ['palidez', 'edad_meses'],
    fidelidad: 'adaptado',
  },
  {
    id: 'IMCI-NUT-01',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => possiblyAge(f, 2, 60) && !isPregnant(f) && !isPostpartum(f) && has(f, 'hinchazon_ambos_pies'),
    explicacion: { es: 'Niño de 2 meses a 5 años con hinchazón de ambos pies (posible desnutrición aguda grave complicada).', nah: '' },
    accion: { es: `${REFER_NOW} Mantenerlo abrigado.`, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 10 del PDF, "Oedema of both feet → COMPLICATED SEVERE ACUTE MALNUTRITION, refer URGENTLY"; ${CITE.ICCM}, p. 6 ("Swelling of both feet")`,
    fuente_url: SRC.IMCI_2014,
    needs: ['hinchazon_ambos_pies', 'edad_meses'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-Y-CIRC-01',
    block: 'general_danger',
    level: 'centro_hoy',
    applies: (f) =>
      (knownAge(f, 0, 2) || possiblyAge(f, years(5))) && anyOf(f, 'no_puede_beber', 'vomita_todo', 'palidez_intensa'),
    explicacion: { es: 'No puede beber, vomita todo o tiene palidez intensa (mayor de 5 años o bebé menor de 2 meses).', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. Ofrecer sorbos pequeños de Vida Suero Oral mientras tanto.', nah: '' },
    fuente: `${CITE.IITT}, criterios amarillos "Circulation": "Unable to feed or drink", "Vomits everything", "Severe pallor" (tablas adulto y pediátrica; la pediátrica incluye al lactante <2 meses); ${CITE.NOM_007}, num. 5.6.1.9 ("vómito" del recién nacido)`,
    fuente_url: SRC.IITT_ADULT,
    needs: ['no_puede_beber', 'vomita_todo', 'palidez_intensa', 'edad_meses'],
    fidelidad: 'adaptado',
  },
  {
    // Respuesta "Sí" a la revisión de signos de peligro (src/triage/screening.ts), que el motor pregunta antes de
    // "Atender aquí". Cada signo de la lista ya es urgencia por su propia regla a esa edad:
    //   2 meses a <5 años: IMCI-GDS-02 (no puede beber ni mamar), IMCI-GDS-03 (vomita todo), GEN-CONV-01 (convulsiones),
    //                      IMCI-GDS-01 / GEN-UNC-01 (muy dormido / no despierta).
    //   5 años o más: IITT-R-RESP-01 / GEN-CYAN-01 (respirar / labios morados), CDC-HEART-01 (pecho, solo ≥12 años),
    //                 GEN-CONV-01, GEN-UNC-01 / CDC-STROKE-01 (no despierta / confusión), CDC-STROKE-01 (cara, un lado,
    //                 habla), GEN-BLEED-01 (sangrado abundante).
    //   Edad desconocida: la unión de las dos listas.
    // El extractor y el LLM nunca marcan esta clave (no está en SYMPTOMS).
    id: 'PAHTLI-GDS-SCREEN',
    block: 'general_danger',
    level: 'urgencia',
    applies: (f) => has(f, SCREENING_KEY),
    explicacion: { es: 'Usted confirmó al menos un signo de peligro de la lista. Cualquiera de ellos necesita atención urgente.', nah: '' },
    accion: { es: `${REFER_NOW} Anote cuál de los signos tiene para decirlo al llegar.`, nah: '' },
    fuente: `${CITE.IMCI_2014}, p. 2 impresa / p. 5 del PDF, "Check for general danger signs" (2 meses a 5 años: no puede beber ni mamar, vomita todo, convulsiones, letárgico o inconsciente; "Any general danger sign… Refer URGENTLY"); ${CITE.ICCM}, p. 6 ("Danger signs"); 5 años o más: ${CITE.IITT}, criterios rojos ("Unresponsive", "Respiratory distress* or central cyanosis", "Heavy bleeding", "Active convulsions") y CDC (infarto y derrame cerebral: "Call 9-1-1")`,
    fuente_url: SRC.IMCI_2014,
    needs: [SCREENING_KEY],
    // adaptado: una sola pregunta resume varios signos; en ≥5 años la lista combina IITT rojo y CDC (ver docs/decisiones-clinicas.md #20).
    fidelidad: 'adaptado',
  },
];
