import type { Rule } from './types';
import { anyOf, has, hasFever, isNum, isPostpartum, isPregnant } from './helpers';
import { CITE, SRC } from './sources';

const REFER_OBS =
  'URGENCIA OBSTÉTRICA: trasladar AHORA al hospital con atención obstétrica (llamar al 911 o activar el plan de traslado de la comunidad). Llevar su carnet perinatal. Acompañarla.';

const NOM007_5313 = `${CITE.NOM_007}, num. 5.3.1.3 ("Identificar signos y síntomas de urgencia obstétrica…")`;
const PCPNC_C15 = `${CITE.WHO_PCPNC_2015}, cuadro C15 "Advise on danger signs" (p. 44 del PDF)`;
const PCPNC_D28 = `${CITE.WHO_PCPNC_2015}, cuadro D28 "Advise on danger signs" posparto (p. 64 del PDF)`;
const IMSS_GRR = `${CITE.IMSS_GPC_PRENATAL}, p. 9 del PDF (signos de alarma: "debe acudir inmediatamente a un hospital o centro de salud")`;

const EMB = ['embarazada'];

export const PREGNANCY_RULES: Rule[] = [
  {
    id: 'NOM007-EMB-01',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && anyOf(f, 'sangrado_vaginal', 'sangrado_abundante'),
    explicacion: { es: 'Embarazada con sangrado por la vagina.', nah: '' },
    accion: { es: `${REFER_OBS} Que vaya acostada sobre su lado izquierdo.`, nah: '' },
    fuente: `${NOM007_5313}: "hemorragia transvaginal"; ${PCPNC_C15}: "vaginal bleeding" → ir de inmediato; ${CITE.IITT}: embarazada con "Heavy bleeding" = rojo`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'sangrado_vaginal'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NOM007-EMB-02',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => (isPregnant(f) || isPostpartum(f)) && anyOf(f, 'dolor_cabeza_intenso', 'dolor_cabeza_subito'),
    explicacion: { es: 'Embarazada o recién parida con dolor de cabeza muy fuerte (posible preeclampsia).', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${NOM007_5313}: "cefalea intensa"; ${PCPNC_C15}: "severe headaches with blurred vision"; ${CITE.IITT}: embarazada con "Severe headache" = rojo; ${IMSS_GRR}: "Fuerte dolor de cabeza"`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'dolor_cabeza_intenso'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMSS-EMB-01',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => (isPregnant(f) || isPostpartum(f)) && anyOf(f, 'vision_borrosa', 'zumbido_oidos'),
    explicacion: { es: 'Embarazada o recién parida que ve borroso, ve lucecitas o le zumban los oídos (posible preeclampsia).', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${IMSS_GRR}: "Zumbido en el oído", "Visión borrosa con puntos de lucecitas"; ${CITE.IITT}: embarazada con "Visual changes" = rojo; ${PCPNC_C15}`,
    fuente_url: SRC.IMSS_GPC_PRENATAL,
    needs: [...EMB, 'vision_borrosa', 'zumbido_oidos'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NOM007-EMB-03',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && has(f, 'salida_liquido_vaginal'),
    explicacion: { es: 'Embarazada con salida de líquido por la vagina (posible ruptura de la fuente).', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${NOM007_5313}: "pérdida transvaginal de líquido o sangre"; ${IMSS_GRR}: "Pérdida de líquido o sangre por la vagina"`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'salida_liquido_vaginal'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NOM007-EMB-04',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && anyOf(f, 'dolor_abdominal', 'dolor_abdominal_intenso'),
    explicacion: { es: 'Embarazada con dolor de panza (bajo vientre).', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${NOM007_5313}: "dolor abdominal"; ${IMSS_GRR}: "Dolor abdominal persistente (en el bajo vientre) de cualquier intensidad"; ${PCPNC_C15}: "severe abdominal pain"`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'dolor_abdominal'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NOM007-EMB-05',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && hasFever(f),
    explicacion: { es: 'Embarazada con fiebre.', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${NOM007_5313}: "fiebre" entre los signos de urgencia obstétrica; ${IMSS_GRR}: "Fiebre". (OMS PCPNC C15 la gradúa "lo antes posible" si no hay postración: ver limitaciones)`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'fiebre', 'temperatura_c'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NOM007-EMB-06',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && has(f, 'palidez_intensa'),
    explicacion: { es: 'Embarazada con palidez intensa.', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${NOM007_5313}: "palidez intensa"; ${IMSS_GRR}: "Palidez marcada"`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'palidez_intensa'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMSS-EMB-02',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) =>
      isPregnant(f) && has(f, 'movimientos_fetales_disminuidos') && (!isNum(f.semanas_embarazo) || f.semanas_embarazo >= 28),
    explicacion: { es: 'Embarazo de 28 semanas o más y el bebé se mueve menos o no se ha movido en más de 2 horas.', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${IMSS_GRR}: "Disminución o ausencia de movimientos fetales por más de 2 horas… embarazo mayor de 28 semanas"; ${CITE.WHO_PCPNC_2015}, cuadro C7 (refiere si no hay movimiento NI latido fetal; la promotora no puede auscultar el latido, por eso se refiere)`,
    fuente_url: SRC.IMSS_GPC_PRENATAL,
    needs: [...EMB, 'movimientos_fetales_disminuidos', 'semanas_embarazo'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IMSS-EMB-03',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && has(f, 'contracciones'),
    explicacion: { es: 'Embarazada con contracciones (antes de 37 semanas: amenaza de parto prematuro; a término: trabajo de parto).', nah: '' },
    accion: { es: `${REFER_OBS} El parto debe atenderse en una unidad con personal calificado.`, nah: '' },
    fuente: `${IMSS_GRR}: "Contracciones uterinas… antes de las 37 semanas"; ${CITE.NOM_007}, num. 5.3.1.13.3 (amenaza de parto pretérmino = urgencia obstétrica); ${CITE.IITT}: embarazada con "Active labour" = rojo`,
    fuente_url: SRC.IMSS_GPC_PRENATAL,
    needs: [...EMB, 'contracciones'],
    fidelidad: 'adaptado',
  },
  {
    id: 'WHO-PCPNC-EMB-01',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && has(f, 'vomita_todo'),
    explicacion: { es: 'Embarazada que vomita todo (vómito intenso).', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${CITE.WHO_PCPNC_2015}, cuadro B2 "Quick check" (p. 22 del PDF): "severe vomiting" → EMERGENCY FOR WOMAN`,
    fuente_url: SRC.WHO_PCPNC_2015,
    needs: [...EMB, 'vomita_todo'],
    fidelidad: 'verbatim',
  },
  {
    id: 'WHO-PCPNC-EMB-02',
    block: 'pregnancy',
    level: 'centro_hoy',
    applies: (f) => (isPregnant(f) || isPostpartum(f)) && has(f, 'hinchazon_cara_manos'),
    explicacion: { es: 'Embarazada o recién parida con hinchazón de cara, manos o piernas.', nah: '' },
    accion: {
      es: 'Llevar HOY a la unidad de salud para tomar la presión. Si además tiene dolor de cabeza fuerte, ve borroso o le zumban los oídos: URGENCIA.',
      nah: '',
    },
    fuente: `${PCPNC_C15}: "swelling of fingers, face, legs" → "go to the health centre as soon as possible"; ${IMSS_GRR}: "Hinchazón de pies, manos o cara" (la GPC dice "inmediatamente": ver docs 4.1); posparto: ${CITE.NOM_007}, num. 5.6.2.2 (vigilar la presión arterial en el puerperio)`,
    fuente_url: SRC.WHO_PCPNC_2015,
    needs: [...EMB, 'posparto', 'hinchazon_cara_manos'],
    // adaptado: IMSS GRR dice "inmediatamente" y OMS "lo antes posible"; se extiende al posparto.
    fidelidad: 'adaptado',
  },
  {
    id: 'IMSS-EMB-04',
    block: 'pregnancy',
    level: 'centro_hoy',
    applies: (f) => isPregnant(f) && anyOf(f, 'vomito_persistente', 'ardor_orinar'),
    explicacion: { es: 'Embarazada con vómitos frecuentes o ardor/molestia al orinar.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud para valoración.', nah: '' },
    fuente: `${IMSS_GRR}: "Náuseas y vómitos frecuentes", "Aumento en el número de micciones y molestia al orinar"`,
    fuente_url: SRC.IMSS_GPC_PRENATAL,
    needs: [...EMB, 'vomito_persistente', 'ardor_orinar'],
    fidelidad: 'adaptado',
  },
  // ── Posparto (hasta 6 semanas) ────────────────────────────────────────────
  {
    id: 'WHO-PCPNC-PP-01',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) =>
      isPostpartum(f) &&
      anyOf(f, 'sangrado_abundante', 'sangrado_aumenta', 'dolor_pantorrilla', 'dolor_pecho', 'dificultad_respirar', 'dolor_abdominal_intenso'),
    explicacion: {
      es: 'Recién parida con sangrado abundante o que aumenta en vez de disminuir, dolor/hinchazón de pantorrilla, dolor de pecho, dificultad para respirar o dolor de panza muy fuerte.',
      nah: '',
    },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${PCPNC_D28}: "vaginal bleeding: more than 2 or 3 pads soaked in 20-30 minutes… OR bleeding increases rather than decreases after delivery", "fast or difficult breathing", "severe abdominal pain", "calf pain, redness or swelling, shortness of breath or chest pain" → ir de inmediato`,
    fuente_url: SRC.WHO_PCPNC_2015,
    needs: ['posparto', 'sangrado_abundante', 'sangrado_aumenta', 'dolor_pantorrilla', 'dolor_pecho', 'dificultad_respirar', 'dolor_abdominal_intenso'],
    fidelidad: 'verbatim',
  },
  {
    id: 'WHO-PCPNC-PP-02',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPostpartum(f) && hasFever(f) && has(f, 'debilidad_general'),
    explicacion: { es: 'Recién parida con fiebre y tan débil que no se puede levantar.', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${PCPNC_D28}: "fever and too weak to get out of bed" → ir de inmediato`,
    fuente_url: SRC.WHO_PCPNC_2015,
    needs: ['posparto', 'fiebre', 'debilidad_general'],
    context: ['fiebre'],
    fidelidad: 'verbatim',
  },
  {
    id: 'WHO-PCPNC-PP-03',
    block: 'pregnancy',
    level: 'centro_hoy',
    applies: (f) =>
      isPostpartum(f) &&
      (hasFever(f) || anyOf(f, 'dolor_abdominal', 'pechos_rojos_dolorosos', 'flujo_mal_olor', 'ardor_orinar', 'dolor_cabeza')),
    explicacion: {
      es: 'Recién parida con fiebre, dolor de panza, pechos rojos o dolorosos, flujo con mal olor, ardor al orinar o dolor de cabeza persistente.',
      nah: '',
    },
    accion: { es: 'Llevar HOY a la unidad de salud. Si tiene sangrado abundante, convulsiones o no se puede levantar: URGENCIA.', nah: '' },
    fuente: `${PCPNC_D28}: "Go to health centre as soon as possible if: fever, abdominal pain, … breasts swollen, red or tender…, foul-smelling lochia"; ${CITE.NOM_007}, num. 5.6.1.9 (madre: "fiebre, hemorragia, cefalea persistente")`,
    fuente_url: SRC.WHO_PCPNC_2015,
    needs: ['posparto', 'fiebre', 'dolor_abdominal', 'pechos_rojos_dolorosos', 'flujo_mal_olor', 'ardor_orinar', 'dolor_cabeza'],
    fidelidad: 'verbatim',
  },
  {
    id: 'WHO-PCPNC-PP-04',
    block: 'pregnancy',
    level: 'centro_hoy',
    applies: (f) => isPostpartum(f) && has(f, 'depresion_grave'),
    explicacion: { es: 'Recién parida con tristeza profunda o depresión grave.', nah: '' },
    accion: { es: 'Llevar HOY a la unidad de salud. No dejarla sola con el bebé si está muy mal. Si dice que se quiere morir o hacerse daño: URGENCIA.', nah: '' },
    fuente: `${PCPNC_D28}: "Go to health centre as soon as possible if… severe depression or suicidal behaviour (ideas or attempts)"`,
    fuente_url: SRC.WHO_PCPNC_2015,
    needs: ['posparto', 'depresion_grave', 'ideas_suicidas'],
    context: ['depresion_grave'],
    fidelidad: 'verbatim',
  },
  {
    id: 'NOM007-EMB-07',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => (isPregnant(f) || isPostpartum(f)) && has(f, 'dolor_epigastrio'),
    explicacion: { es: 'Embarazada o recién parida con dolor en la boca del estómago (posible preeclampsia grave).', nah: '' },
    accion: { es: REFER_OBS, nah: '' },
    fuente: `${NOM007_5313}: "epigastralgia"`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'dolor_epigastrio'],
    // adaptado: la NOM la lista en el embarazo; se extiende al puerperio (la preeclampsia puede aparecer después del parto).
    fidelidad: 'adaptado',
  },
  {
    id: 'NOM007-EMB-08',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && anyOf(f, 'desmayo', 'confusion', 'letargico'),
    explicacion: { es: 'Embarazada que se desmayó, está confundida o muy adormilada (pérdida o alteración de la conciencia).', nah: '' },
    accion: { es: `${REFER_OBS} Acostarla sobre su lado izquierdo.`, nah: '' },
    fuente: `${NOM007_5313}: "pérdida de la conciencia"; ${CITE.IITT} (≥12 años), rojo "PREGNANT WITH ANY OF: Seizures or altered mental status"`,
    fuente_url: SRC.NOM_007,
    needs: [...EMB, 'desmayo', 'confusion'],
    fidelidad: 'verbatim',
  },
  {
    id: 'IITT-R-PREG-TRAUMA-01',
    block: 'pregnancy',
    level: 'urgencia',
    applies: (f) => isPregnant(f) && anyOf(f, 'golpe_caida', 'trauma_grave', 'fractura', 'quemadura'),
    explicacion: { es: 'Embarazada que se cayó, recibió un golpe (sobre todo en la panza) o tiene otra lesión.', nah: '' },
    accion: {
      es: `${REFER_OBS} Preguntar con calma y en privado si alguien la lastimó; si es así, también necesita protección.`,
      nah: '',
    },
    fuente: `${CITE.IITT} (≥12 años), rojo "PREGNANT WITH ANY OF: … Trauma"`,
    fuente_url: SRC.IITT_ADULT,
    needs: [...EMB, 'golpe_caida', 'trauma_grave'],
    fidelidad: 'verbatim',
  },
];
