/** URLs de las fuentes primarias consultadas (descargadas y leídas al construir las reglas, oct-2026). */
export const SRC = {
  IMCI_2014: 'https://cdn.who.int/media/docs/default-source/mca-documents/child/imci-integrated-management-of-childhood-illness/imci-in-service-training/imci-chart-booklet.pdf',
  IMCI_YI_2019: 'https://iris.who.int/server/api/core/bitstreams/e5a2ace4-c5ae-462d-b28c-1ac1d1a351ca/content',
  ICCM: 'https://www.childhealthtaskforce.org/sites/default/files/2019-06/Caring%20for%20Sick%20Child%20in%20the%20Community%20CHW%20Chart%20Booklet%28WHO%2CUNICEF%2C2014%29.pdf',
  NOM_031: 'https://hist.cndh.org.mx/sites/default/files/doc/Programas/VIH/Leyes%20y%20normas%20y%20reglamentos/Norma%20Oficial%20Mexicana/NOM-031-SSA2-1999%20Salud%20del%20ni%C3%B1o.pdf',
  NOM_007: 'https://www.gob.mx/cms/uploads/attachment/file/512098/NOM-007-SSA2-2016.pdf',
  IMSS_GPC_PRENATAL: 'https://www.imss.gob.mx/sites/all/statics/guiasclinicas/028GRR.pdf',
  WHO_PCPNC_2015: 'https://iris.who.int/server/api/core/bitstreams/e9f751fd-6eab-42cb-9e0c-0eb86a0365bb/content',
  PAHO_DENGUE_2020: 'https://www.paho.org/sites/default/files/2020-09/2020-cde-algoritmos-manejo-clinico-dengue.pdf',
  IITT_ADULT: 'https://cdn.who.int/media/docs/default-source/integrated-health-services-(ihs)/csy/iitt/iitt_adult.pdf?sfvrsn=b2a91431_1',
  IITT_PED: 'https://cdn.who.int/media/docs/default-source/integrated-health-services-(ihs)/csy/iitt/iitt_pediatric.pdf?sfvrsn=15161bfb_1',
  /** Copia del IITT con la tarjeta de referencia ("Signs of Respiratory Distress"), publicada por el hospital ZOL (Bélgica); leída oct-2026. */
  IITT_REFCARD: 'https://www.zol.be/sites/default/files/deelsites/urgentiegeneeskunde/iitt_triage.pdf',
  CDC_STROKE: 'https://www.cdc.gov/stroke/signs-symptoms/index.html',
  CDC_HEART_ATTACK: 'https://www.cdc.gov/heart-disease/about/heart-attack.html',
  NICE_NG143: 'https://www.nice.org.uk/guidance/ng143',
  WHO_DIARRHOEA_2005: 'https://iris.who.int/server/api/core/bitstreams/df59ceab-2498-4a64-bd93-ad7566addb4e/content',
  WHO_MHGAP_2016: 'https://iris.who.int/server/api/core/bitstreams/6ded7ffd-9d69-493a-b48a-0b3e6250c173/content',
  IMSS_SARAMPION: 'https://www.imss.gob.mx/sites/all/statics/salud/infografiasl/Sarampion-personal-institucional.pdf',
  // Ronda 3 (4-oct-2026): fuentes de docs/research-common-complaints.md, descargadas y leídas otra vez al escribir las reglas.
  SSA_IAVYS_2026: 'https://www.gob.mx/cms/uploads/attachment/file/1073814/Manual_de_Tratamiento_de_las_IAVyS.pdf',
  DGE_ALACRAN_2012: 'https://cevece.edomex.gob.mx/sites/cevece.edomex.gob.mx/files/files/docs/marco_juridico/manualesvep/Manual_Picadura_Alacran.pdf',
  CENAPRECE_LOXO: 'https://www.cenaprece.salud.gob.mx/programas/interior/vectores/otrasenf/AspectosGeneralesAranaViolinista.html',
  SSA_RABIA_GUIA: 'https://transparencia.info.jalisco.gob.mx/sites/default/files/GUIA%20PARA%20LA%20PERSONA%20EXPUETA%20AL%20VIRUS%20DE%20LA%20RABIA.pdf',
  NOM_015: 'https://dof.gob.mx/nota_detalle.php?codigo=5168074&fecha=23/11/2010',
  NOM_030: 'https://dof.gob.mx/nota_detalle.php?codigo=5144642&fecha=31/05/2010',
  NOM_006: 'https://dof.gob.mx/nota_detalle.php?codigo=5321934&fecha=13/11/2013',
  IMSS_031: 'https://www.imss.gob.mx/sites/all/statics/guiasclinicas/031GRR.pdf',
  IMSS_040: 'https://www.imss.gob.mx/sites/all/statics/guiasclinicas/040GRR.pdf',
  IMSS_042: 'https://www.imss.gob.mx/sites/all/statics/guiasclinicas/042GRR.pdf',
  IMSS_045: 'https://www.imss.gob.mx/sites/all/statics/guiasclinicas/045GRR.pdf',
  IMSS_062: 'https://www.imss.gob.mx/sites/all/statics/guiasclinicas/062GRR.pdf',
  IMSS_077: 'https://www.imss.gob.mx/sites/all/statics/guiasclinicas/077GRR.pdf',
  WHO_BURNS_FS: 'https://www.who.int/news-room/fact-sheets/detail/burns',
  NHS_STOMACH: 'https://www.nhs.uk/conditions/stomach-ache/',
  NHS_BLOATING: 'https://www.nhs.uk/conditions/bloating/',
  NHS_CONSTIPATION: 'https://www.nhs.uk/conditions/constipation/',
  NHS_FLATULENCE: 'https://www.nhs.uk/conditions/flatulence/',
  NHS_HEARTBURN: 'https://www.nhs.uk/conditions/heartburn-and-acid-reflux/',
  NHS_NAUSEA: 'https://www.nhs.uk/symptoms/feeling-sick-nausea/',
  NHS_DIARRHOEA_VOMITING: 'https://www.nhs.uk/conditions/diarrhoea-and-vomiting/',
  NHS_HEADACHES: 'https://www.nhs.uk/symptoms/headaches/',
  NHS_COLD: 'https://www.nhs.uk/conditions/common-cold/',
  NHS_COUGH: 'https://www.nhs.uk/conditions/cough/',
  NHS_SORE_THROAT: 'https://www.nhs.uk/conditions/sore-throat/',
  NHS_EARACHE: 'https://www.nhs.uk/conditions/earache/',
  NHS_UTI: 'https://www.nhs.uk/conditions/urinary-tract-infections-utis/',
  NHS_BACK_PAIN: 'https://www.nhs.uk/conditions/back-pain/',
  NHS_TOOTHACHE: 'https://www.nhs.uk/conditions/toothache/',
  NHS_HIVES: 'https://www.nhs.uk/conditions/hives/',
  NHS_INSECT_BITES: 'https://www.nhs.uk/conditions/insect-bites-and-stings/',
  NHS_CUTS: 'https://www.nhs.uk/conditions/cuts-and-grazes/',
  NHS_BURNS: 'https://www.nhs.uk/conditions/burns-and-scalds/',
  NHS_HEAD_INJURY: 'https://www.nhs.uk/conditions/head-injury-and-concussion/',
  NHS_DIZZINESS: 'https://www.nhs.uk/symptoms/dizziness/',
  NHS_HYPO: 'https://www.nhs.uk/conditions/low-blood-sugar-hypoglycaemia/',
  NHS_PANIC: 'https://www.nhs.uk/mental-health/conditions/panic-disorder/',
} as const;

/** Cita corta reutilizable (el detalle de página/sección va en cada regla). */
export const CITE = {
  IMCI_2014: 'OMS/UNICEF, AIEPI (IMCI) Chart Booklet, 2014',
  IMCI_YI_2019: 'OMS, AIEPI: manejo del lactante enfermo de hasta 2 meses, Chart Booklet 2019',
  ICCM: 'OMS/UNICEF, Caring for the sick child in the community (AIEPI comunitario), Chart Booklet 2014',
  NOM_031: 'NOM-031-SSA2-1999, Para la atención a la salud del niño (DOF 09-02-2001)',
  NOM_007: 'NOM-007-SSA2-2016, Atención de la mujer durante el embarazo, parto y puerperio (DOF 07-04-2016)',
  IMSS_GPC_PRENATAL: 'GPC IMSS-028-08 Control prenatal con atención centrada en la paciente, GRR act. 2017',
  WHO_PCPNC_2015: 'OMS, Pregnancy, Childbirth, Postpartum and Newborn Care (PCPNC), 3a ed. 2015',
  PAHO_DENGUE_2020: 'OPS, Algoritmos para el manejo clínico de los casos de dengue, 2020 (basado en Guía OPS 2016)',
  IITT: 'OMS/CICR/MSF, Interagency Integrated Triage Tool (IITT)',
  CDC_STROKE: 'CDC, Signs and Symptoms of Stroke',
  CDC_HEART_ATTACK: 'CDC, About Heart Attack Symptoms, Risk, and Recovery',
  NICE_NG143: 'NICE NG143, Fever in under 5s: assessment and initial management (2019, act. 2021)',
  WHO_DIARRHOEA_2005: 'OMS, The treatment of diarrhoea: a manual for physicians and other senior health workers, 4a rev. 2005',
  WHO_MHGAP_2016: 'OMS, mhGAP Intervention Guide 2.0, 2016',
  IMSS_SARAMPION: 'IMSS, Sarampión: información para personal institucional (infografía, consultada oct-2026)',
  SSA_IAVYS_2026: 'Secretaría de Salud/CENAPRECE, Guía de diagnóstico y tratamiento de la intoxicación por arácnidos y ofidios, 2026',
  DGE_ALACRAN_2012: 'SSA/DGE, Manual de Procedimientos Estandarizados para la Vigilancia Epidemiológica de la Intoxicación por Picadura de Alacrán, 2012',
  CENAPRECE_LOXO: 'CENAPRECE, Loxoscelismo: aspectos generales y medidas de prevención (araña violinista), mod. 2016',
  SSA_RABIA_GUIA: 'SSA/CENAPRECE, Guía para la atención médica y antirrábica de la persona expuesta al virus de la rabia, 2a ed. 2010',
  NOM_015: 'NOM-015-SSA2-2010, Para la prevención, tratamiento y control de la diabetes mellitus (DOF 23-11-2010)',
  NOM_030: 'NOM-030-SSA2-2009, Hipertensión arterial sistémica (DOF 31-05-2010)',
  NOM_006: 'NOM-006-SSA2-2013, Para la prevención y control de la tuberculosis (DOF 13-11-2013)',
  IMSS_031: 'GPC IMSS-031-08 Diagnóstico de apendicitis aguda, GRR',
  IMSS_040: 'GPC IMSS-040-08 Diagnóstico y tratamiento del paciente "Gran Quemado", GRR',
  IMSS_042: 'GPC IMSS-042-08 Intestino irritable en el adulto, GRR',
  IMSS_045: 'GPC IMSS-045-08 Lumbalgia aguda y crónica en el primer nivel, GRR',
  IMSS_062: 'GPC IMSS-062-08 Infección aguda de vías aéreas superiores (3 meses a 18 años), GRR act. 2016',
  IMSS_077: 'GPC IMSS-077-08 Infección aguda no complicada del tracto urinario en la mujer, GRR',
  WHO_BURNS_FS: 'OMS, Burns (nota descriptiva, 13-oct-2023)',
  NHS: 'NHS (Reino Unido), página de salud',
} as const;
